### ISSUE TITLE
Implement maintanance mode

### ISSUE THREAD

**Issue by michael** [substance/archivist#40]
We need a mechanism to turn system into maintenance mode... it should be a switch in the admin panel. The flag if maintenance mode is on or not could be stored in the db? in a system document maybe?

When maintenance is on all API's are blocked for regular users.. only admins have access. the apis should return an error message: "System is in maintenance mode, please try again later".

**Comment by Integral** [comment]
Ok, just commit very ugly implementation of maintenance stuff on server.
Short brief:
we have new model type ```system```, it's not strict and have only one property name which is indexed
and we have few methods db.getSystemVariable and db.setSystemVariable
we also have method for set maintenance mode, it'll listen /api/maintenance, you have to make get request with ```on``` param true or false. If it is true then it'll also populate ```user``` with your user id, otherwise with null.
and we have mode.checkCurrentMode, which is now attached to remove, update, create functions of document and remove, update, merge of subjects
so, if we are in maintenance mode and try to use those apis it'll return 503 with your messsage

**Comment by michael** [comment]
UI for switcher:


![image](https://cloud.githubusercontent.com/assets/2931/5837738/f05725f2-a181-11e4-8ee1-dafae6046b41.png)

**Comment by michael** [comment]
Actually it's **"maintenance"**
