### ISSUE TITLE
UX Improvement: should we show occurrences of subjects in content?

### ISSUE THREAD

**Issue by oliver----** [substance/archivist#70]
At the moment, the subject panel summary is not very useful, as it provides no interactions.
I assume that it might be useful to find subject annotations - even in the editor.

**Comment by Integral** [comment]
@michael?

**Comment by michael** [comment]
I thought about it.. but didn't act since I don't know what would be a useful behavior.. when you click on a subject entry..  we could highlight all occurences in the docs which may involve highlighting multiple subject brackets at the same time and also use highlights in the outline. I need to make sure that there's a good visual distiction between highlighted and activated subject_references.

**Comment by oliver----** [comment]
I believe for today's release it is not essential.
But maybe we can come up with such improvements soon?
